package sshconf_test

import (
	"testing"

	"github.com/GavinYangAI/hopd/internal/config"
	"github.com/GavinYangAI/hopd/internal/sshconf"
)

func TestGenerateChain(t *testing.T) {
	cfg, err := config.Parse([]byte(`
hosts:
  bastionB:
    host: 203.0.113.9
    user: userB
  entryA:
    host: 198.51.100.7
    port: 65522
    user: userA
    key: ~/.ssh/idA
    jump: bastionB
groups:
  prod:
    - name: pg
      local: "5432"
      remote: 10.0.1.5:5432
      via_host: entryA
`))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	tun, _ := cfg.Tunnel("pg")
	text, entry, err := sshconf.Generate(cfg, tun)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if entry != "entryA" {
		t.Fatalf("entry = %q, want entryA", entry)
	}
	want := `# Generated by hopd — do not edit. Source: config.yaml
Host entryA
    HostName 198.51.100.7
    Port 65522
    User userA
    IdentityFile ~/.ssh/idA
    IdentitiesOnly yes
    ProxyJump bastionB
Host bastionB
    HostName 203.0.113.9
    Port 22
    User userB
`
	if text != want {
		t.Fatalf("generated mismatch:\n--- got ---\n%s\n--- want ---\n%s", text, want)
	}
}

func TestGenerateLegacyReturnsEmpty(t *testing.T) {
	cfg, _ := config.Parse([]byte(`
groups:
  g:
    - {name: t1, local: "5432", remote: x:5432, via: somealias}
`))
	tun, _ := cfg.Tunnel("t1")
	text, entry, err := sshconf.Generate(cfg, tun)
	if err != nil || text != "" || entry != "" {
		t.Fatalf("legacy tunnel should yield empty: text=%q entry=%q err=%v", text, entry, err)
	}
}
