// Package sshconf renders hopd's reusable host model into an ssh config file
// that hopd owns and passes to ssh via -F, plus parses the user's ~/.ssh/config
// for the GUI import wizard. It never writes the user's ~/.ssh/config.
package sshconf

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/GavinYangAI/hopd/internal/config"
)

const header = "# Generated by hopd — do not edit. Source: config.yaml\n"

// Generate renders the ssh -F config for a via_host tunnel's host chain and
// returns the config text plus the entry Host alias to use as the ssh
// destination. For a tunnel without ViaHost (legacy via/jump), it returns
// ("", "", nil), signalling the caller to use the legacy argv path.
func Generate(cfg *config.Config, t config.Tunnel) (text, entry string, err error) {
	if t.ViaHost == "" {
		return "", "", nil
	}
	var b strings.Builder
	b.WriteString(header)
	seen := map[string]bool{}
	for name := t.ViaHost; name != ""; {
		if seen[name] {
			return "", "", fmt.Errorf("host %q: jump chain has a cycle", name)
		}
		seen[name] = true
		h, ok := cfg.Host(name)
		if !ok {
			return "", "", fmt.Errorf("via_host references unknown host %q", name)
		}
		writeHostBlock(&b, name, h)
		name = h.Jump
	}
	return b.String(), t.ViaHost, nil
}

func writeHostBlock(b *strings.Builder, name string, h config.Host) {
	fmt.Fprintf(b, "Host %s\n", name)
	fmt.Fprintf(b, "    HostName %s\n", h.Host)
	if h.Port != 0 {
		fmt.Fprintf(b, "    Port %s\n", strconv.Itoa(h.Port))
	}
	if h.User != "" {
		fmt.Fprintf(b, "    User %s\n", h.User)
	}
	if h.Key != "" {
		fmt.Fprintf(b, "    IdentityFile %s\n", h.Key)
		b.WriteString("    IdentitiesOnly yes\n")
	}
	if h.Jump != "" {
		fmt.Fprintf(b, "    ProxyJump %s\n", h.Jump)
	}
	keys := make([]string, 0, len(h.SSHOptions))
	for k := range h.SSHOptions {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(b, "    %s %s\n", k, h.SSHOptions[k])
	}
}
