package config

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"
)

// marshalShape is the on-disk YAML structure Marshal emits. It mirrors the
// shape Parse reads, so Marshal->Parse round-trips.
type marshalShape struct {
	Defaults marshalDefaults            `yaml:"defaults,omitempty"`
	Hosts    map[string]marshalHost     `yaml:"hosts,omitempty"`
	Groups   map[string][]marshalTunnel `yaml:"groups"`
}

type marshalHost struct {
	Host       string            `yaml:"host"`
	Port       int               `yaml:"port,omitempty"`
	User       string            `yaml:"user,omitempty"`
	Key        string            `yaml:"key,omitempty"`
	Jump       string            `yaml:"jump,omitempty"`
	SSHOptions map[string]string `yaml:"ssh_options,omitempty"`
}

type marshalDefaults struct {
	SSHOptions map[string]string `yaml:"ssh_options,omitempty"`
	Restart    *marshalRestart   `yaml:"restart,omitempty"`
}

type marshalRestart struct {
	Min string `yaml:"min"`
	Max string `yaml:"max"`
}

type marshalTunnel struct {
	Name       string            `yaml:"name"`
	Local      string            `yaml:"local"`
	Remote     string            `yaml:"remote"`
	Via        string            `yaml:"via,omitempty"`
	Jump       []string          `yaml:"jump,omitempty"`
	ViaHost    string            `yaml:"via_host,omitempty"`
	SSHOptions map[string]string `yaml:"ssh_options,omitempty"`
	Autostart  bool              `yaml:"autostart,omitempty"`
}

// Marshal serializes a Config back to YAML. It writes the retained defaults and,
// per tunnel, only the ssh_options that differ from the defaults — so the output
// re-parses to an equivalent Config without duplicating default options.
func Marshal(c *Config) ([]byte, error) {
	shape := marshalShape{Groups: map[string][]marshalTunnel{}}

	if len(c.defaultOpts) > 0 {
		shape.Defaults.SSHOptions = c.defaultOpts
	}
	shape.Defaults.Restart = &marshalRestart{
		Min: c.Restart.Min.String(),
		Max: c.Restart.Max.String(),
	}

	if len(c.hosts) > 0 {
		shape.Hosts = make(map[string]marshalHost, len(c.hosts))
		for name, h := range c.hosts {
			shape.Hosts[name] = marshalHost{
				Host:       h.Host,
				Port:       h.Port,
				User:       h.User,
				Key:        h.Key,
				Jump:       h.Jump,
				SSHOptions: h.SSHOptions,
			}
		}
	}

	for _, t := range c.tunnels {
		mt := marshalTunnel{
			Name:      t.Name,
			Local:     t.Local,
			Remote:    t.Remote,
			Via:       t.Via,
			Jump:      t.Jump,
			ViaHost:   t.ViaHost,
			Autostart: t.Autostart,
		}
		opts := map[string]string{}
		for k, v := range t.SSHOptions {
			if dv, ok := c.defaultOpts[k]; ok && dv == v {
				continue
			}
			opts[k] = v
		}
		if len(opts) > 0 {
			mt.SSHOptions = opts
		}
		shape.Groups[t.Group] = append(shape.Groups[t.Group], mt)
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by hopd-gui — edits here are overwritten on save.\n")
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(shape); err != nil {
		return nil, fmt.Errorf("marshal config: %w", err)
	}
	_ = enc.Close()
	return buf.Bytes(), nil
}

// reindex rebuilds byName from tunnels (call after any mutation).
func (c *Config) reindex() {
	c.byName = make(map[string]int, len(c.tunnels))
	for i, t := range c.tunnels {
		c.byName[t.Name] = i
	}
}

// AddTunnel appends a tunnel. It errors if the name already exists.
func (c *Config) AddTunnel(t Tunnel) error {
	if _, ok := c.byName[t.Name]; ok {
		return fmt.Errorf("tunnel %q already exists", t.Name)
	}
	c.tunnels = append(c.tunnels, t)
	c.reindex()
	return nil
}

// UpdateTunnel replaces the tunnel currently named oldName with t. Renaming is
// allowed as long as the new name doesn't collide with a different tunnel.
func (c *Config) UpdateTunnel(oldName string, t Tunnel) error {
	i, ok := c.byName[oldName]
	if !ok {
		return fmt.Errorf("tunnel %q not found", oldName)
	}
	if t.Name != oldName {
		if _, exists := c.byName[t.Name]; exists {
			return fmt.Errorf("tunnel %q already exists", t.Name)
		}
	}
	c.tunnels[i] = t
	c.reindex()
	return nil
}

// RemoveTunnel deletes the named tunnel.
func (c *Config) RemoveTunnel(name string) error {
	i, ok := c.byName[name]
	if !ok {
		return fmt.Errorf("tunnel %q not found", name)
	}
	c.tunnels = append(c.tunnels[:i], c.tunnels[i+1:]...)
	c.reindex()
	return nil
}
